#!/bin/bash -

PROJECT_DIR=$(pwd)
SOURCE_DIR=$PROJECT_DIR/tool
BUILD_DIR=$PROJECT_DIR/tool/build

if [ ! -d "$BUILD_DIR" ]; then
  echo "Generating tool/build dir"
  mkdir $BUILD_DIR
fi

echo "Compiling $SOURCE_DIR into $BUILD_DIR"
javac -d $BUILD_DIR $SOURCE_DIR/*.java

echo "Running with output dir $PROJECT_DIR/src"
java -classpath $BUILD_DIR jlox.tool.GenerateAst $PROJECT_DIR/src

