#!/bin/bash - 

PROJECT_DIR=$(pwd)
SOURCE_DIR=$PROJECT_DIR/src
BUILD_DIR=$PROJECT_DIR/build

if [ ! -d "$BUILD_DIR" ]; then
  mkdir build
fi

javac -d $BUILD_DIR $SOURCE_DIR/*.java
java -classpath $BUILD_DIR jlox.Lox $1
