#!/bin/bash - 

PROJECT_DIR=$(pwd)
SOURCE_DIR=$PROJECT_DIR/src
BUILD_DIR=$PROJECT_DIR/build

if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD_DIR
fi

javac -d $BUILD_DIR $SOURCE_DIR/*.java

if [ "$1" == "-p" ]; then
  java -classpath $BUILD_DIR jlox.AstPrinter $2
else
  java -classpath $BUILD_DIR jlox.Lox $1
fi
